name: Deploy Quartz site

on:
  push:
    branches:
      - web-publish
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Quartz
        run: |
          cd quartz
          npm install
      - name: Prepare content for Quartz
        run: |
          rm -rf quartz/content
          mkdir -p quartz/content

          # copy everything except quartz itself
          rsync -av \
            --exclude='quartz' \
            --exclude='.git' \
            ./ quartz/content/

      - name: Build site
        run: |
          cd quartz
          npx quartz build

      - name: Deploy to gh-pages
        run: |
          cd quartz/public
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy site"
          git branch -M gh-pages
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -f origin gh-pages
